# Generated by Django 4.2.7 on 2025-07-18 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("auth_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Connexion réussie"),
                            ("LOGIN_FAILED", "Échec de connexion"),
                            ("LOGOUT", "Déconnexion"),
                            ("PASSWORD_CHANGED", "Mot de passe modifié"),
                            ("EMAIL_VERIFIED", "Email vérifié"),
                            ("ACCOUNT_CREATED", "Compte créé"),
                            ("SESSION_CREATED", "Session créée"),
                            ("SESSION_DELETED", "Session supprimée"),
                            ("SUSPICIOUS_LOGIN", "Connexion suspecte"),
                            ("MULTIPLE_FAILED_LOGINS", "Multiples échecs de connexion"),
                            (
                                "PASSWORD_BREACH_ATTEMPT",
                                "Tentative de violation de mot de passe",
                            ),
                            ("ACCOUNT_LOCKOUT", "Verrouillage de compte"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal de sécurité",
                "verbose_name_plural": "Journaux de sécurité",
                "db_table": "auth_security_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
