# Generated by Django 4.2.7 on 2025-07-24 23:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("shared_models", "0002_invoice_paymenttransaction_invoiceitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
